spring:
  application:
    name: catalog-application

  datasource:
    url: jdbc:mysql://localhost:3306/catalog_app?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: GMT

server:
  port: 8080

